// ─────────────────────────────────────────────────────────────────────────────
// Mock Venue Provider
// ─────────────────────────────────────────────────────────────────────────────
// Deterministic dataset of fictional pubs.  Every call returns the same data.
// Replace this class with a real Places/venue API provider when ready — the
// PubCrawlPlanner only depends on the VenueProvider interface.
// ─────────────────────────────────────────────────────────────────────────────

import type { PlannerVenue, VenueProvider } from './types'

// Fictional pubs spread around a city-centre reference point
// (lat ~51.509, lng ~-0.134 — generic city coordinates).
// Distances range from 0.15 km to 1.45 km from the centre.
const MOCK_PUBS: PlannerVenue[] = [
  {
    id: 'pub-001',
    name: 'The Golden Fox',
    lat: 51.5102,
    lng: -0.1312,
    rating: 4.7,
    priceLevel: 2,
    openingTime: '12:00',
    closingTime: '23:30',
    atmosphere: ['lively', 'classic', 'welcoming'],
    tags: ['real-ale', 'craft-beer', 'pub-quiz', 'dog-friendly'],
    estimatedCostPerPerson: 7,
    capacity: 'large',
    features: ['outdoor-seating', 'pool-table', 'fireplace'],
    distanceFromCentre: 0.28,
  },
  {
    id: 'pub-002',
    name: 'The Anchor House',
    lat: 51.5088,
    lng: -0.1358,
    rating: 4.5,
    priceLevel: 2,
    openingTime: '11:00',
    closingTime: '00:00',
    atmosphere: ['cosy', 'nautical', 'relaxed'],
    tags: ['cocktails', 'spirits', 'board-games'],
    estimatedCostPerPerson: 8,
    capacity: 'medium',
    features: ['fireplace', 'vintage-decor', 'board-games'],
    distanceFromCentre: 0.41,
  },
  {
    id: 'pub-003',
    name: 'The Lantern',
    lat: 51.5115,
    lng: -0.1289,
    rating: 4.6,
    priceLevel: 2,
    openingTime: '16:00',
    closingTime: '01:00',
    atmosphere: ['lively', 'modern', 'social'],
    tags: ['craft-beer', 'live-music', 'sports'],
    estimatedCostPerPerson: 7,
    capacity: 'large',
    features: ['live-music', 'sports-screen', 'outdoor-seating'],
    distanceFromCentre: 0.22,
  },
  {
    id: 'pub-004',
    name: 'The Crown & Compass',
    lat: 51.5076,
    lng: -0.1301,
    rating: 4.5,
    priceLevel: 2,
    openingTime: '12:00',
    closingTime: '23:00',
    atmosphere: ['classic', 'traditional', 'welcoming'],
    tags: ['real-ale', 'sunday-roast', 'pub-quiz'],
    estimatedCostPerPerson: 6,
    capacity: 'medium',
    features: ['pool-table', 'fireplace', 'garden'],
    distanceFromCentre: 0.34,
  },
  {
    id: 'pub-005',
    name: 'The Old Station',
    lat: 51.5062,
    lng: -0.1345,
    rating: 4.3,
    priceLevel: 1,
    openingTime: '10:00',
    closingTime: '23:00',
    atmosphere: ['historic', 'spacious', 'classic'],
    tags: ['real-ale', 'cider', 'dog-friendly'],
    estimatedCostPerPerson: 5,
    capacity: 'large',
    features: ['outdoor-seating', 'historic-building', 'fireplace'],
    distanceFromCentre: 0.55,
  },
  {
    id: 'pub-006',
    name: 'The Harbour Arms',
    lat: 51.5121,
    lng: -0.1268,
    rating: 4.8,
    priceLevel: 3,
    openingTime: '14:00',
    closingTime: '01:00',
    atmosphere: ['upscale', 'lively', 'trendy'],
    tags: ['cocktails', 'craft-beer', 'live-music', 'events'],
    estimatedCostPerPerson: 11,
    capacity: 'large',
    features: ['rooftop', 'live-music', 'cocktail-bar', 'events'],
    distanceFromCentre: 0.19,
  },
  {
    id: 'pub-007',
    name: 'The Red Lion',
    lat: 51.5094,
    lng: -0.1378,
    rating: 4.4,
    priceLevel: 2,
    openingTime: '11:00',
    closingTime: '23:30',
    atmosphere: ['classic', 'friendly', 'local'],
    tags: ['real-ale', 'darts', 'pub-quiz'],
    estimatedCostPerPerson: 6,
    capacity: 'medium',
    features: ['darts', 'pool-table', 'beer-garden'],
    distanceFromCentre: 0.48,
  },
  {
    id: 'pub-008',
    name: 'The Copper Tap',
    lat: 51.5108,
    lng: -0.1321,
    rating: 4.6,
    priceLevel: 2,
    openingTime: '15:00',
    closingTime: '01:30',
    atmosphere: ['modern', 'social', 'vibrant'],
    tags: ['craft-beer', 'spirits', 'cocktails'],
    estimatedCostPerPerson: 9,
    capacity: 'medium',
    features: ['craft-beer-taps', 'cocktail-bar', 'live-dj'],
    distanceFromCentre: 0.31,
  },
  {
    id: 'pub-009',
    name: 'The Malt & Vine',
    lat: 51.5068,
    lng: -0.1289,
    rating: 4.4,
    priceLevel: 3,
    openingTime: '17:00',
    closingTime: '00:30',
    atmosphere: ['intimate', 'sophisticated', 'relaxed'],
    tags: ['wine-bar', 'cocktails', 'spirits'],
    estimatedCostPerPerson: 12,
    capacity: 'small',
    features: ['wine-cellar', 'quiet-area', 'candles'],
    distanceFromCentre: 0.62,
  },
  {
    id: 'pub-010',
    name: 'The Bricklayers Arms',
    lat: 51.5081,
    lng: -0.1265,
    rating: 4.2,
    priceLevel: 1,
    openingTime: '09:00',
    closingTime: '23:00',
    atmosphere: ['local', 'down-to-earth', 'unpretentious'],
    tags: ['real-ale', 'sports', 'darts'],
    estimatedCostPerPerson: 4,
    capacity: 'medium',
    features: ['sports-screen', 'darts', 'pool-table'],
    distanceFromCentre: 0.72,
  },
  {
    id: 'pub-011',
    name: 'The Velvet Underground',
    lat: 51.5127,
    lng: -0.1304,
    rating: 4.7,
    priceLevel: 3,
    openingTime: '18:00',
    closingTime: '02:00',
    atmosphere: ['alternative', 'lively', 'eclectic'],
    tags: ['live-music', 'cocktails', 'craft-beer', 'events'],
    estimatedCostPerPerson: 10,
    capacity: 'large',
    features: ['live-music', 'late-night', 'dancefloor', 'events'],
    distanceFromCentre: 0.38,
  },
  {
    id: 'pub-012',
    name: 'The Half Moon',
    lat: 51.5055,
    lng: -0.1312,
    rating: 4.3,
    priceLevel: 2,
    openingTime: '12:00',
    closingTime: '23:00',
    atmosphere: ['cosy', 'traditional', 'friendly'],
    tags: ['real-ale', 'cider', 'dog-friendly', 'pub-quiz'],
    estimatedCostPerPerson: 6,
    capacity: 'medium',
    features: ['beer-garden', 'fireplace', 'dog-friendly'],
    distanceFromCentre: 0.87,
  },
  {
    id: 'pub-013',
    name: 'The Silk Road',
    lat: 51.5098,
    lng: -0.1251,
    rating: 4.5,
    priceLevel: 3,
    openingTime: '16:00',
    closingTime: '01:00',
    atmosphere: ['exotic', 'vibrant', 'social'],
    tags: ['cocktails', 'spirits', 'craft-beer'],
    estimatedCostPerPerson: 11,
    capacity: 'medium',
    features: ['cocktail-bar', 'mood-lighting', 'events'],
    distanceFromCentre: 0.78,
  },
  {
    id: 'pub-014',
    name: 'The Forge & Anvil',
    lat: 51.5072,
    lng: -0.1368,
    rating: 4.4,
    priceLevel: 2,
    openingTime: '11:00',
    closingTime: '23:30',
    atmosphere: ['industrial', 'modern', 'casual'],
    tags: ['craft-beer', 'real-ale', 'sports'],
    estimatedCostPerPerson: 7,
    capacity: 'large',
    features: ['outdoor-seating', 'sports-screen', 'large-tables'],
    distanceFromCentre: 0.59,
  },
  {
    id: 'pub-015',
    name: 'The White Rabbit',
    lat: 51.5134,
    lng: -0.1345,
    rating: 4.6,
    priceLevel: 2,
    openingTime: '15:00',
    closingTime: '00:30',
    atmosphere: ['quirky', 'eclectic', 'lively'],
    tags: ['craft-beer', 'cocktails', 'board-games', 'events'],
    estimatedCostPerPerson: 8,
    capacity: 'medium',
    features: ['board-games', 'themed-decor', 'private-hire'],
    distanceFromCentre: 0.44,
  },
  {
    id: 'pub-016',
    name: 'The Dock & Dram',
    lat: 51.5048,
    lng: -0.1291,
    rating: 4.3,
    priceLevel: 2,
    openingTime: '12:00',
    closingTime: '23:00',
    atmosphere: ['maritime', 'relaxed', 'classic'],
    tags: ['whisky', 'real-ale', 'sports'],
    estimatedCostPerPerson: 7,
    capacity: 'medium',
    features: ['whisky-selection', 'fireplace', 'outdoor-seating'],
    distanceFromCentre: 1.12,
  },
]

export class MockVenueProvider implements VenueProvider {
  /**
   * Returns the mock pub dataset.
   * `activityId` is accepted for interface compliance — future providers will
   * filter by activity type. `location` is accepted but ignored here; real
   * providers will use it to query nearby venues.
   */
  async getVenues(
    _activityId: string,
    _location?: { lat: number; lng: number },
  ): Promise<PlannerVenue[]> {
    // Deterministic: same input → same output, every time.
    return MOCK_PUBS
  }
}
